#include "esp_adc/adc_oneshot.h"

#define WIFI_DISCONNECT_LED_GPIO 14
#define HEARTBEAT_LED_GPIO 13
#define RESET_BUTTON_GPIO 25
#define HEARTRATE_SENSOR_ADC_CHANNEL 6
#define PRESSURE_SENSOR_SCK_PIN 17
#define PRESSURE_SENSOR_OUT_PIN 16
#define I2C_SCL_PIN 22
#define I2C_SDA_PIN 21

#define ADC_ATTEN ADC_ATTEN_DB_11
#define HEARTBEAT_THRESHOLD 3000
#define REQUIRED_HEARTBEATS 7
#define HEARTBEAT_TIMEOUT_MS 2000